### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by kabulkurniawan** [pbonte/C-Sprite#2]
Hi, 

I have a problem during installation of C-Sprite, I tried to follow the readme instruction but I got this error massage:

C:\Users\MyName\C-Sprite\target>java -cp CSprite-0.0.1-SNAPSHOT-jar-with-dependencies.jar be.ugent.idlab.csprite.CSpriteTest ../experiments/debs/dbpedia_stripped3.owl ../experiments/debs/dbpedia_nolonglines.nt "http://dbpedia.org/ontology/Work"

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.NullPointerException
        at be.ugent.idlab.csprite.parser.ConceptHandler.getSubsTypes(ConceptHandler.java:36)
        at be.ugent.idlab.csprite.parser.HierarchyGenerator.getSupTypes(HierarchyGenerator.java:83)
        at be.ugent.idlab.csprite.CSpriteEngine.addQuery(CSpriteEngine.java:65)
        at be.ugent.idlab.csprite.CSpriteTest.main(CSpriteTest.java:63)

any idea?

**Comment by pbonte** [comment]
Hi,

On a first glance, I see there was an old version of the dataset in the readme. Step 2 should now be:
"unzip the triples.zip file in experiments/debs" instead of edbt. (updated in the readme)

Let me know if this solves it.

**Comment by kabulkurniawan** [comment]
edbt or debs?

in the readme, it's written debs in the beginning.

java -cp CSprite-0.0.1-SNAPSHOT-jar-with-dependencies.jar be.ugent.idlab.csprite.CSpriteTest ../experiments/debs/dbpedia_stripped3.owl ../experiments/debs/dbpedia_nolonglines.nt "http://dbpedia.org/ontology/Work"

still doesn't work

**Comment by pbonte** [comment]
Yes, because I updated the README while writing you.

I updated the code, there might have been something wrong with the preprocessing of the prefixes.
Let me know if it works now. Otherwise, tell me what system you are using.

KR,
Pieter

**Comment by kabulkurniawan** [comment]
Okay, Now it works, thanks!

just a question, is the engine support for full standard SPARQL-Query?

thanks

**Comment by kabulkurniawan** [comment]
also, 
if I have 5 different SPARQL-Queries and want to register them at the same time, how should I do?
it's not clearly explained in the documentation.

thanks in advance!

**Comment by pbonte** [comment]
Hi,

No, we are still working towards  SPARQL1.1 support.
Currently, C-Sprite is only an efficient reasoning engine to perform hierarchical (subclass-relations) reasoning over RDF data streams. This means that the query is a single concept from the ontology.
If you need to join the triples afterwards, you can pipe C-Sprite with a sparql endpoint (e.g. Apache Jena) and let the later perform the joins. C-Sprite should then be used to filter (using hierarchical reasoning) those concepts from the stream that are relevant for further processing.

If you are interested in this, let me know.

Also, what is the complexity of your SPARQL queries? If you just aim to simply join triples, this can be added rather easily.

KR,
Pieter

**Comment by kabulkurniawan** [comment]
Hi, thanks for your explanation,
Actually,  I am working on low-level to a high-level event extraction (e.g. from log sources), and formulate a number of nested SPARQL-Construct queries to generate those high-level events.   

Currently, we used C-SPARQL engine to make it but it seems the correctness is decreasing while the number of a triple is increasing in a certain time window.

we are still looking for another alternative RDF-stream reasoning engine to solve this problem.

**Comment by pbonte** [comment]
Hi,

Interesting use case!

So, in the short term this is what I can do for you: I can pipeline C-Sprite with apache jena, this allows you to register SPARQL-Construct queries, C-Sprite will select those triples in the stream that are relevant and forward them to jena to perform the joins. 
This was something that was on my todo-list anyway, so I'll increase its priority for now, so you can check if C-Sprite is an option for your case.

Just a few questions so I can provide a prototype with the least amount of effort:
* Are you using sliding or tumbling windows?
* Is hierarchical reasoning enough for your use case, i.e. subclass-of inferences?
* What input and output do you require? Currently file-based and websockets.
* Can you give me an example of these nested queries?

**Comment by kabulkurniawan** [comment]
Hi, 

Sure, 

Are you using sliding or tumbling windows? -> yes, we need to "catch" & generate those events streamingly.
Is hierarchical reasoning enough for your use case, i.e. subclass-of inferences? -> I think is enough for now
What input and output do you require? Currently file-based and websockets. -> we process the output from [TripleWave](https://streamreasoning.github.io/TripleWave/) which is Websockets
Can you give me an example of these nested queries?  ->  could you provide me with an email address? We could discuss this further and I can send you my previous work.

Best,
K. Kurniawan

**Comment by pbonte** [comment]
Sure,

You can contact me on pieter.bonte [at] ugent.be
